import 'package:flutter/material.dart';

const unreadActivityPanelKey = Key('unread-activity-panel');
const unreadActivityClearButtonKey = Key('unread-activity-clear-button');
const unreadActivityMoreButtonKey = Key('unread-activity-more-button');
const unreadActivitySheetKey = Key('unread-activity-sheet');
const homeProgressSummaryKey = Key('home-progress-summary');
const homeProgressSummaryCtaKey = Key('home-progress-summary-cta');
const homeBrandLogoKey = Key('home-brand-logo');
const homeMenuButtonKey = Key('home-menu-button');
const homeMenuSheetKey = Key('home-menu-sheet');
const homeMenuCuriosityButtonKey = Key('home-menu-curiosity-button');
const homeMenuStockStoryButtonKey = Key('home-menu-stock-story-button');
const homeMenuImprovementButtonKey = Key('home-menu-improvement-button');
const homeMenuBalanceButtonKey = Key('home-menu-balance-button');
const homeMenuProfileCardButtonKey = Key('home-menu-profile-card-button');
const homeMenuWishlistButtonKey = Key('home-menu-wishlist-button');
const homeMenuGuideButtonKey = Key('home-menu-guide-button');
const firstVisitGuideSheetKey = Key('first-visit-guide-sheet');
const firstVisitGuideStartButtonKey = Key('first-visit-guide-start-button');
const firstVisitGuideTourButtonKey = Key('first-visit-guide-tour-button');
